title: DPEA Softdev Training Docs
description: The DPEA's introductory training for software development students 
theme: just-the-docs

url: https://dpengineering.github.io/softdev-training/
enable_copy_code_button: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
callouts:
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  warning:
    title: Warning!
    color: red
logo: "assets/Images/engineeringGear.png"
favicon_ico: "/engineeringGear.ico"






